import 'package:flutter/material.dart';

import '../model/catalog_item.dart';

class CatalogViewModel extends ChangeNotifier {
  List<CatalogItem> catalog = [
    CatalogItem(
        id: 0,
        name: "Золотое кольцо с бриллиантами",
        shortDesc: "Белое золото 585 пробы.",
        description: "Кольцо с 21 бриллиантом, огранка круг 17 граней, 0.047 карат, цвет 2, чистота 2, тип огранки Б;\nБелое золото 585 пробы.",
        price: "5490",
        categories: ["Позолота"],
        sizeList: [
          "15",
          "15.5",
          "16",
          "16.5",
          "17",
          "17.5",
          "18",
          "18.5",
          "19",
          "19.5",
          "20",
          "20.5",
          "21",
          "21.5",
        ],
        brand: "Бриллианты Якутии by Sergey Gribnyakov",
        weight: 0.5,
        material: "Белое золото",
        rating: 5,
        image: "https://g2.sunlight.net/media/products/9a26f515163d1fbfe32ddcc2e09fb59cdfd3b69e.jpg"),
    CatalogItem(
        id: 1,
        name: "Золотая цепь",
        shortDesc: "Розовое золото 585 пробы",
        description: "Цепь",
        price: "23725",
        categories: ["Серебро"],
        sizeList: [
          "40",
          "45",
          "50",
          "55",
          "60",
          "65",
        ],
        brand: "KRASTSVETMET",
        weight: 6.26,
        material: "Розовое золото",
        rating: 4,
        image: "https://g4.sunlight.net/media/products/91688923a1a08fa268a72e449be8a894eaf645da.jpg"),
    CatalogItem(
        id: 2,
        name: "Золотой крест-подвеска с бриллиантами",
        shortDesc: "Подвеска с 4 бриллиантами",
        description: "wdwerewrerwerwerad",
        price: "16990",
        categories: ["Золото", "Платина"],
        sizeList: ["10", "10.5", "11", "12", "13.5", "14", "15.5"],
        brand: "brand",
        weight: 20,
        material: "Золото",
        rating: 4,
        image: "https://g8.sunlight.net/media/products/f4388acbd68b8f8dfe39c86185f772d39b7c7bea.jpg"),
    CatalogItem(
        id: 3,
        name: "Золотые серьги с сапфирами и бриллиантами",
        shortDesc: "Розовое золото 585 пробы",
        description: "wdwerewrerwerwerad",
        price: "21990",
        categories: ["Золото", "Платина"],
        sizeList: ["10", "10.5", "11", "12", "13.5", "14", "15.5"],
        brand: "brand",
        weight: 20,
        material: "Золото",
        rating: 4,
        image: "https://g6.sunlight.net/media/products/e3d093b4da5c33160b067d110c88404bc057302a.jpg"),
    CatalogItem(
        id: 4,
        name: "Золотое кольцо с сапфирами и бриллиантами",
        shortDesc: "Розовое золото 585 пробы",
        description: "wdwerewrerwerwerad",
        price: "10990",
        categories: ["Золото", "Платина"],
        sizeList: ["10", "10.5", "11", "12", "13.5", "14", "15.5"],
        brand: "brand",
        weight: 20,
        material: "Золото",
        rating: 4,
        image: "https://g8.sunlight.net/media/products/88ae0c4a2fff3eec664be082fb8e1d9d9de2f192.jpg"),
    CatalogItem(
        id: 5,
        name: "Золотое шейное украшение с ониксом",
        shortDesc: "Желтое золото 585 пробы",
        description: "wdwerewrerwerwerad",
        price: "32990",
        categories: ["Золото", "Платина"],
        sizeList: ["10", "10.5", "11", "12", "13.5", "14", "15.5"],
        brand: "brand",
        weight: 20,
        material: "Золото",
        rating: 4,
        image: "https://g0.sunlight.net/media/products/44e8ee78f89e3abf7e98f77ea3dd3e11c8dd5775.jpg"),
  ];
}
